In [1]:
import yfinance as yf
dat = yf.Ticker("GOOG")

/Users/alexei/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [7]:
dat.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-09-14 00:00:00-04:00,339.109985,346.450012,338.739990,345.709991,22484400,0.0,0.0
2026-09-15 00:00:00-04:00,343.339996,344.359985,339.179993,341.429993,13361000,0.0,0.0
2026-09-16 00:00:00-04:00,343.359985,344.700012,337.450012,339.359985,12869700,0.0,0.0
2026-09-17 00:00:00-04:00,345.000000,345.964996,340.500000,343.679993,15315700,0.0,0.0
2026-09-18 00:00:00-04:00,351.220001,355.130005,343.869995,344.410004,34108900,0.0,0.0
2026-09-21 00:00:00-04:00,346.190002,353.299988,344.799988,350.869995,18252200,0.0,0.0
2026-09-22 00:00:00-04:00,353.239990,359.980011,345.739990,347.410004,20165100,0.0,0.0
2026-09-23 00:00:00-04:00,346.299988,346.329987,334.200012,334.980011,23283400,0.0,0.0
2026-09-24 00:00:00-04:00,333.000000,339.309998,332.809998,339.010010,15965000,0.0,0.0
2026-09-25 00:00:00-04:00,338.924988,343.600006,337.910004,341.079987,13858700,0.0,0.0
2026-09-28 00:00:00-04:00,337.600006,340.109985,336.600006,339.160004,13870800,0.0,0.0
2026-09-29 00:00:00-04:00,338.540009,339.640015,335.019989,337.320007,14002300,0.0,0.0
2026-09-30 00:00:00-04:00,340.649994,349.054993,337.720001,340.739990,24240100,0.0,0.0
2026-10-01 00:00:00-04:00,347.755005,350.093994,332.649994,334.929993,20045000,0.0,0.0
2026-10-02 00:00:00-04:00,338.100006,342.779999,337.959991,340.350006,17497900,0.0,0.0
2026-10-05 00:00:00-04:00,339.209991,344.989990,339.149994,343.829987,13982200,0.0,0.0
2026-10-06 00:00:00-04:00,344.640015,345.670013,341.700012,344.589996,13177400,0.0,0.0
2026-10-07 00:00:00-04:00,343.679993,347.609985,340.279999,347.369995,11344700,0.0,0.0
2026-10-08 00:00:00-04:00,349.644989,353.529999,343.510010,344.859985,13987000,0.0,0.0
2026-10-09 00:00:00-04:00,348.000000,351.059998,346.880005,347.859985,11142900,0.0,0.0
2026-10-12 00:00:00-04:00,348.339996,352.660004,347.160004,348.970001,11854200,0.0,0.0
2026-10-13 00:00:00-04:00,352.415009,354.500000,347.570007,349.519989,14409500,0.0,0.0
2026-10-14 00:00:00-04:00,351.545013,355.250000,348.739990,349.346893,3624974,0.0,0.0

In [5]:
yf.download(['GOOG'], period='max')

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            GOOG        GOOG        GOOG        GOOG       GOOG
Date
2004-08-19    2.475684    2.567467    2.367617    2.467295  897427216
2004-08-20    2.672328    2.691326    2.479632    2.492215  458857488
2004-08-23    2.699221    2.799886    2.690585    2.732529  366857939
2004-08-24    2.587452    2.753501    2.555377    2.744619  306396159
2004-08-25    2.615333    2.664679    2.563026    2.589673  184645512
...                ...         ...         ...         ...        ...
2026-10-08  344.859985  353.529999  343.510010  349.644989   13987000
2026-10-09  347.859985  351.059998  346.880005  348.000000   11142900
2026-10-12  348.970001  352.660004  347.160004  348.339996   11854200
2026-10-13  349.519989  354.500000  347.570007  352.415009   14409500
2026-10-14  349.000000  355.250000  348.910004  351.545013    3553812

[5574 rows x 5 columns]

In [8]:
dat.history(period='max')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2004-08-19 00:00:00-04:00,2.467294,2.567466,2.367616,2.475684,897427216,0.0,0.0
2004-08-20 00:00:00-04:00,2.492215,2.691325,2.479632,2.672328,458857488,0.0,0.0
2004-08-23 00:00:00-04:00,2.732529,2.799886,2.690585,2.699221,366857939,0.0,0.0
2004-08-24 00:00:00-04:00,2.744619,2.753501,2.555378,2.587453,306396159,0.0,0.0
2004-08-25 00:00:00-04:00,2.589673,2.664679,2.563026,2.615333,184645512,0.0,0.0
...,...,...,...,...,...,...,...
2026-10-08 00:00:00-04:00,349.644989,353.529999,343.510010,344.859985,13987000,0.0,0.0
2026-10-09 00:00:00-04:00,348.000000,351.059998,346.880005,347.859985,11142900,0.0,0.0
2026-10-12 00:00:00-04:00,348.339996,352.660004,347.160004,348.970001,11854200,0.0,0.0
2026-10-13 00:00:00-04:00,352.415009,354.500000,347.570007,349.519989,14409500,0.0,0.0
2026-10-14 00:00:00-04:00,351.545013,355.250000,348.739990,349.440002,3626034,0.0,0.0

In [9]:
dat = yf.Ticker("MSFT")
dat.history(period='max')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13 00:00:00-05:00,0.053745,0.061649,0.053745,0.059014,1031788800,0.0,0.0
1986-03-14 00:00:00-05:00,0.059014,0.062176,0.059014,0.061122,308160000,0.0,0.0
1986-03-17 00:00:00-05:00,0.061122,0.062703,0.061122,0.062176,133171200,0.0,0.0
1986-03-18 00:00:00-05:00,0.062176,0.062703,0.060068,0.060595,67766400,0.0,0.0
1986-03-19 00:00:00-05:00,0.060595,0.061122,0.059014,0.059541,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2026-10-08 00:00:00-04:00,529.809998,533.510010,518.789978,522.609985,20228700,0.0,0.0
2026-10-09 00:00:00-04:00,528.239990,537.219971,526.239990,535.070007,18500600,0.0,0.0
2026-10-12 00:00:00-04:00,537.530029,542.739990,535.700012,541.150024,18314900,0.0,0.0
2026-10-13 00:00:00-04:00,544.640015,551.150024,543.059998,543.450012,23824500,0.0,0.0
2026-10-14 00:00:00-04:00,545.150024,545.739990,538.960022,540.090027,3665906,0.0,0.0